// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// summ
double summ(NumericMatrix a);
RcppExport SEXP _cWR_summ(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(summ(a));
    return rcpp_result_gen;
END_RCPP
}
// outerm
double outerm(NumericMatrix a, NumericMatrix b);
RcppExport SEXP _cWR_outerm(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(outerm(a, b));
    return rcpp_result_gen;
END_RCPP
}
// nsubmat
NumericMatrix nsubmat(NumericMatrix a, int low, int up, int column);
RcppExport SEXP _cWR_nsubmat(SEXP aSEXP, SEXP lowSEXP, SEXP upSEXP, SEXP columnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type low(lowSEXP);
    Rcpp::traits::input_parameter< int >::type up(upSEXP);
    Rcpp::traits::input_parameter< int >::type column(columnSEXP);
    rcpp_result_gen = Rcpp::wrap(nsubmat(a, low, up, column));
    return rcpp_result_gen;
END_RCPP
}
// loopsum
NumericMatrix loopsum(NumericMatrix a, int nv, NumericVector njv);
RcppExport SEXP _cWR_loopsum(SEXP aSEXP, SEXP nvSEXP, SEXP njvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njv(njvSEXP);
    rcpp_result_gen = Rcpp::wrap(loopsum(a, nv, njv));
    return rcpp_result_gen;
END_RCPP
}
// offsubmat
NumericMatrix offsubmat(NumericMatrix a, int b, int d);
RcppExport SEXP _cWR_offsubmat(SEXP aSEXP, SEXP bSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< int >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(offsubmat(a, b, d));
    return rcpp_result_gen;
END_RCPP
}
// offsubmat_col
NumericMatrix offsubmat_col(NumericMatrix a, int b);
RcppExport SEXP _cWR_offsubmat_col(SEXP aSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(offsubmat_col(a, b));
    return rcpp_result_gen;
END_RCPP
}
// sumsubmat
NumericMatrix sumsubmat(NumericMatrix a);
RcppExport SEXP _cWR_sumsubmat(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sumsubmat(a));
    return rcpp_result_gen;
END_RCPP
}
// multMat
NumericVector multMat(NumericMatrix m1, NumericMatrix m2);
RcppExport SEXP _cWR_multMat(SEXP m1SEXP, SEXP m2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type m2(m2SEXP);
    rcpp_result_gen = Rcpp::wrap(multMat(m1, m2));
    return rcpp_result_gen;
END_RCPP
}
// sumsubmat_col
NumericMatrix sumsubmat_col(NumericMatrix a);
RcppExport SEXP _cWR_sumsubmat_col(SEXP aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type a(aSEXP);
    rcpp_result_gen = Rcpp::wrap(sumsubmat_col(a));
    return rcpp_result_gen;
END_RCPP
}
// cond1
NumericMatrix cond1(NumericVector cat_c, NumericVector y2_c, NumericVector y2_t);
RcppExport SEXP _cWR_cond1(SEXP cat_cSEXP, SEXP y2_cSEXP, SEXP y2_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cat_c(cat_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_c(y2_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_t(y2_tSEXP);
    rcpp_result_gen = Rcpp::wrap(cond1(cat_c, y2_c, y2_t));
    return rcpp_result_gen;
END_RCPP
}
// cond3_1
NumericMatrix cond3_1(NumericVector cat_c, NumericVector y2_c, NumericVector y2_t, NumericVector y1_c, NumericVector y1_t);
RcppExport SEXP _cWR_cond3_1(SEXP cat_cSEXP, SEXP y2_cSEXP, SEXP y2_tSEXP, SEXP y1_cSEXP, SEXP y1_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cat_c(cat_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_c(y2_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_t(y2_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_c(y1_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_t(y1_tSEXP);
    rcpp_result_gen = Rcpp::wrap(cond3_1(cat_c, y2_c, y2_t, y1_c, y1_t));
    return rcpp_result_gen;
END_RCPP
}
// cond3_2
NumericMatrix cond3_2(NumericVector cat_c, NumericVector cat_t, NumericVector y2_c, NumericVector y2_t, NumericVector y1_c, NumericVector y1_t);
RcppExport SEXP _cWR_cond3_2(SEXP cat_cSEXP, SEXP cat_tSEXP, SEXP y2_cSEXP, SEXP y2_tSEXP, SEXP y1_cSEXP, SEXP y1_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cat_c(cat_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cat_t(cat_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_c(y2_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_t(y2_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_c(y1_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_t(y1_tSEXP);
    rcpp_result_gen = Rcpp::wrap(cond3_2(cat_c, cat_t, y2_c, y2_t, y1_c, y1_t));
    return rcpp_result_gen;
END_RCPP
}
// cond2
NumericMatrix cond2(NumericVector cat_t, NumericVector y2_c, NumericVector y2_t);
RcppExport SEXP _cWR_cond2(SEXP cat_tSEXP, SEXP y2_cSEXP, SEXP y2_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cat_t(cat_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_c(y2_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_t(y2_tSEXP);
    rcpp_result_gen = Rcpp::wrap(cond2(cat_t, y2_c, y2_t));
    return rcpp_result_gen;
END_RCPP
}
// cond4_1
NumericMatrix cond4_1(NumericVector cat_t, NumericVector y2_c, NumericVector y2_t, NumericVector y1_c, NumericVector y1_t);
RcppExport SEXP _cWR_cond4_1(SEXP cat_tSEXP, SEXP y2_cSEXP, SEXP y2_tSEXP, SEXP y1_cSEXP, SEXP y1_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cat_t(cat_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_c(y2_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_t(y2_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_c(y1_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_t(y1_tSEXP);
    rcpp_result_gen = Rcpp::wrap(cond4_1(cat_t, y2_c, y2_t, y1_c, y1_t));
    return rcpp_result_gen;
END_RCPP
}
// cond4_2
NumericMatrix cond4_2(NumericVector cat_c, NumericVector cat_t, NumericVector y2_c, NumericVector y2_t, NumericVector y1_c, NumericVector y1_t);
RcppExport SEXP _cWR_cond4_2(SEXP cat_cSEXP, SEXP cat_tSEXP, SEXP y2_cSEXP, SEXP y2_tSEXP, SEXP y1_cSEXP, SEXP y1_tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cat_c(cat_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cat_t(cat_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_c(y2_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y2_t(y2_tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_c(y1_cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y1_t(y1_tSEXP);
    rcpp_result_gen = Rcpp::wrap(cond4_2(cat_c, cat_t, y2_c, y2_t, y1_c, y1_t));
    return rcpp_result_gen;
END_RCPP
}
// com_less_Rcpp
NumericVector com_less_Rcpp(NumericVector a, NumericVector b, NumericVector c, NumericVector d);
RcppExport SEXP _cWR_com_less_Rcpp(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(com_less_Rcpp(a, b, c, d));
    return rcpp_result_gen;
END_RCPP
}
// com_more_Rcpp
NumericMatrix com_more_Rcpp(NumericVector a, NumericVector b, NumericVector c, NumericVector d);
RcppExport SEXP _cWR_com_more_Rcpp(SEXP aSEXP, SEXP bSEXP, SEXP cSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type a(aSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type c(cSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(com_more_Rcpp(a, b, c, d));
    return rcpp_result_gen;
END_RCPP
}
// x12GTy12_Rcpp_test
double x12GTy12_Rcpp_test(NumericMatrix win, int nf, int nv, NumericVector njf, NumericVector njv);
RcppExport SEXP _cWR_x12GTy12_Rcpp_test(SEXP winSEXP, SEXP nfSEXP, SEXP nvSEXP, SEXP njfSEXP, SEXP njvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type win(winSEXP);
    Rcpp::traits::input_parameter< int >::type nf(nfSEXP);
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njf(njfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njv(njvSEXP);
    rcpp_result_gen = Rcpp::wrap(x12GTy12_Rcpp_test(win, nf, nv, njf, njv));
    return rcpp_result_gen;
END_RCPP
}
// xi12GTy12_Rcpp_test
double xi12GTy12_Rcpp_test(NumericMatrix win, int nf, int nv, NumericVector njf, NumericVector njv);
RcppExport SEXP _cWR_xi12GTy12_Rcpp_test(SEXP winSEXP, SEXP nfSEXP, SEXP nvSEXP, SEXP njfSEXP, SEXP njvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type win(winSEXP);
    Rcpp::traits::input_parameter< int >::type nf(nfSEXP);
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njf(njfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njv(njvSEXP);
    rcpp_result_gen = Rcpp::wrap(xi12GTy12_Rcpp_test(win, nf, nv, njf, njv));
    return rcpp_result_gen;
END_RCPP
}
// covx12GTy12_Rcpp_test
double covx12GTy12_Rcpp_test(NumericMatrix win1, NumericMatrix win2, int nf, int nv, NumericVector njf, NumericVector njv);
RcppExport SEXP _cWR_covx12GTy12_Rcpp_test(SEXP win1SEXP, SEXP win2SEXP, SEXP nfSEXP, SEXP nvSEXP, SEXP njfSEXP, SEXP njvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type win1(win1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type win2(win2SEXP);
    Rcpp::traits::input_parameter< int >::type nf(nfSEXP);
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njf(njfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njv(njvSEXP);
    rcpp_result_gen = Rcpp::wrap(covx12GTy12_Rcpp_test(win1, win2, nf, nv, njf, njv));
    return rcpp_result_gen;
END_RCPP
}
// covxi12GTy12_Rcpp_test
double covxi12GTy12_Rcpp_test(NumericMatrix win1, NumericMatrix win2, int nf, int nv, NumericVector njf, NumericVector njv);
RcppExport SEXP _cWR_covxi12GTy12_Rcpp_test(SEXP win1SEXP, SEXP win2SEXP, SEXP nfSEXP, SEXP nvSEXP, SEXP njfSEXP, SEXP njvSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type win1(win1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type win2(win2SEXP);
    Rcpp::traits::input_parameter< int >::type nf(nfSEXP);
    Rcpp::traits::input_parameter< int >::type nv(nvSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njf(njfSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type njv(njvSEXP);
    rcpp_result_gen = Rcpp::wrap(covxi12GTy12_Rcpp_test(win1, win2, nf, nv, njf, njv));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _cWR_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_cWR_summ", (DL_FUNC) &_cWR_summ, 1},
    {"_cWR_outerm", (DL_FUNC) &_cWR_outerm, 2},
    {"_cWR_nsubmat", (DL_FUNC) &_cWR_nsubmat, 4},
    {"_cWR_loopsum", (DL_FUNC) &_cWR_loopsum, 3},
    {"_cWR_offsubmat", (DL_FUNC) &_cWR_offsubmat, 3},
    {"_cWR_offsubmat_col", (DL_FUNC) &_cWR_offsubmat_col, 2},
    {"_cWR_sumsubmat", (DL_FUNC) &_cWR_sumsubmat, 1},
    {"_cWR_multMat", (DL_FUNC) &_cWR_multMat, 2},
    {"_cWR_sumsubmat_col", (DL_FUNC) &_cWR_sumsubmat_col, 1},
    {"_cWR_cond1", (DL_FUNC) &_cWR_cond1, 3},
    {"_cWR_cond3_1", (DL_FUNC) &_cWR_cond3_1, 5},
    {"_cWR_cond3_2", (DL_FUNC) &_cWR_cond3_2, 6},
    {"_cWR_cond2", (DL_FUNC) &_cWR_cond2, 3},
    {"_cWR_cond4_1", (DL_FUNC) &_cWR_cond4_1, 5},
    {"_cWR_cond4_2", (DL_FUNC) &_cWR_cond4_2, 6},
    {"_cWR_com_less_Rcpp", (DL_FUNC) &_cWR_com_less_Rcpp, 4},
    {"_cWR_com_more_Rcpp", (DL_FUNC) &_cWR_com_more_Rcpp, 4},
    {"_cWR_x12GTy12_Rcpp_test", (DL_FUNC) &_cWR_x12GTy12_Rcpp_test, 5},
    {"_cWR_xi12GTy12_Rcpp_test", (DL_FUNC) &_cWR_xi12GTy12_Rcpp_test, 5},
    {"_cWR_covx12GTy12_Rcpp_test", (DL_FUNC) &_cWR_covx12GTy12_Rcpp_test, 6},
    {"_cWR_covxi12GTy12_Rcpp_test", (DL_FUNC) &_cWR_covxi12GTy12_Rcpp_test, 6},
    {"_cWR_rcpp_hello_world", (DL_FUNC) &_cWR_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_cWR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
