# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

summ <- function(a) {
    .Call(`_cWR_summ`, a)
}

outerm <- function(a, b) {
    .Call(`_cWR_outerm`, a, b)
}

nsubmat <- function(a, low, up, column) {
    .Call(`_cWR_nsubmat`, a, low, up, column)
}

loopsum <- function(a, nv, njv) {
    .Call(`_cWR_loopsum`, a, nv, njv)
}

offsubmat <- function(a, b, d) {
    .Call(`_cWR_offsubmat`, a, b, d)
}

offsubmat_col <- function(a, b) {
    .Call(`_cWR_offsubmat_col`, a, b)
}

sumsubmat <- function(a) {
    .Call(`_cWR_sumsubmat`, a)
}

multMat <- function(m1, m2) {
    .Call(`_cWR_multMat`, m1, m2)
}

sumsubmat_col <- function(a) {
    .Call(`_cWR_sumsubmat_col`, a)
}

cond1 <- function(cat_c, y2_c, y2_t) {
    .Call(`_cWR_cond1`, cat_c, y2_c, y2_t)
}

cond3_1 <- function(cat_c, y2_c, y2_t, y1_c, y1_t) {
    .Call(`_cWR_cond3_1`, cat_c, y2_c, y2_t, y1_c, y1_t)
}

cond3_2 <- function(cat_c, cat_t, y2_c, y2_t, y1_c, y1_t) {
    .Call(`_cWR_cond3_2`, cat_c, cat_t, y2_c, y2_t, y1_c, y1_t)
}

cond2 <- function(cat_t, y2_c, y2_t) {
    .Call(`_cWR_cond2`, cat_t, y2_c, y2_t)
}

cond4_1 <- function(cat_t, y2_c, y2_t, y1_c, y1_t) {
    .Call(`_cWR_cond4_1`, cat_t, y2_c, y2_t, y1_c, y1_t)
}

cond4_2 <- function(cat_c, cat_t, y2_c, y2_t, y1_c, y1_t) {
    .Call(`_cWR_cond4_2`, cat_c, cat_t, y2_c, y2_t, y1_c, y1_t)
}

com_less_Rcpp <- function(a, b, c, d) {
    .Call(`_cWR_com_less_Rcpp`, a, b, c, d)
}

com_more_Rcpp <- function(a, b, c, d) {
    .Call(`_cWR_com_more_Rcpp`, a, b, c, d)
}

x12GTy12_Rcpp_test <- function(win, nf, nv, njf, njv) {
    .Call(`_cWR_x12GTy12_Rcpp_test`, win, nf, nv, njf, njv)
}

xi12GTy12_Rcpp_test <- function(win, nf, nv, njf, njv) {
    .Call(`_cWR_xi12GTy12_Rcpp_test`, win, nf, nv, njf, njv)
}

covx12GTy12_Rcpp_test <- function(win1, win2, nf, nv, njf, njv) {
    .Call(`_cWR_covx12GTy12_Rcpp_test`, win1, win2, nf, nv, njf, njv)
}

covxi12GTy12_Rcpp_test <- function(win1, win2, nf, nv, njf, njv) {
    .Call(`_cWR_covxi12GTy12_Rcpp_test`, win1, win2, nf, nv, njf, njv)
}

rcpp_hello_world <- function() {
    .Call(`_cWR_rcpp_hello_world`)
}

